# Generated by Django 4.0.6 on 2022-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('hours', models.IntegerField()),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'db_table': 'calendardays',
                'ordering': ['day'],
            },
        ),
    ]
