# Generated by Django 4.0.6 on 2022-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardays',
            name='day',
            field=models.DateField(unique=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='calendardays',
            name='hours',
            field=models.IntegerField(default=8, verbose_name='Рабочие часы'),
        ),
    ]
