# Generated by Django 4.0.6 on 2022-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_event', models.DateTimeField(verbose_name='Начало события')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('event_name', models.CharField(max_length=150, verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'events',
                'ordering': ['start_event'],
            },
        ),
    ]
