# Generated by Django 4.0.6 on 2022-07-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_stop_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='duration',
        ),
    ]
