# Generated by Django 4.0.6 on 2022-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='stop_event',
        ),
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Продолжительность'),
        ),
    ]
