# Generated by Django 4.0.6 on 2022-07-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_stop_event_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Продолжительность'),
        ),
    ]
