# Generated by Django 4.0.6 on 2022-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='important',
            field=models.BooleanField(null=True, verbose_name='Важное событие'),
        ),
    ]
