# Generated by Django 4.0.6 on 2022-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важное событие'),
        ),
    ]
