# Generated by Django 4.0.6 on 2022-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_events_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(help_text='Формат- Часы:Минуты:Секунды', null=True, verbose_name='Продолжительность'),
        ),
    ]
