# Generated by Django 4.0.6 on 2022-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needreload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.IntegerField(verbose_name='Требуется перезагрузка')),
                ('started', models.DateField(verbose_name='Начало')),
                ('ended', models.DateField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Нужна перезагрузка',
                'verbose_name_plural': 'Нужна перезагрузка',
                'db_table': 'need_reload',
            },
        ),
    ]
