# Generated by Django 4.0.6 on 2022-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needreload', '0002_alter_needreload_ended_alter_needreload_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needreload',
            name='started',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
