# Generated by Django 4.0.6 on 2022-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needreload', '0003_alter_needreload_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needreload',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='needreload',
            name='started',
        ),
    ]
