# Generated by Django 4.0.6 on 2022-08-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needreload', '0004_remove_needreload_ended_remove_needreload_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needreload',
            name='required',
            field=models.IntegerField(default=False, verbose_name='Требуется перезагрузка'),
        ),
    ]
