# Generated by Django 4.0.6 on 2022-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
