# Generated by Django 4.0.6 on 2022-08-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_alter_birthday_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='birthdaywishes',
            field=models.CharField(blank=True, default='С днем рождения! Пусть мечты сбываются, счастье не заканчивается, удача не покидает, а близкие всегда будут рядом.', max_length=150),
        ),
    ]
