# Generated by Django 4.0.6 on 2022-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0003_birthday_birthdaywishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthdaywishes',
            field=models.CharField(blank=True, default='С днем рождения! Пусть мечты сбываются, счастье не заканчивается, удача не покидает, а близкие всегда будут рядом.', max_length=150, verbose_name='Пожелания'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='day',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='department',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
    ]
