# Generated by Django 4.0.6 on 2022-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0004_alter_birthday_birthdaywishes_alter_birthday_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/', verbose_name='Фото'),
        ),
    ]
