# Generated by Django 4.0.6 on 2022-08-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0005_birthday_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='foto',
            new_name='photo',
        ),
    ]
