# Generated by Django 4.0.6 on 2022-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0006_rename_foto_birthday_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фото'),
        ),
    ]
