# Generated by Django 4.0.6 on 2022-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0007_alter_birthday_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='photo',
            field=models.ImageField(blank=True, help_text='Размер фото 185х250', upload_to='photo/', verbose_name='Фото'),
        ),
    ]
